/**
 * LGS 2027 — 270 Günlük Benzersiz Motivasyon ve Disiplin Kütüphanesi
 * Yusuf'un zihinsel gücünü, içsel motivasyonunu ve çalışma disiplinini destekleyen
 * 270 adet güne özel, özgün Türkçe ilham sözü.
 *
 * 1 - 90: Alışkanlık, Temel Kurma, İstikrar & Zihinsel Dayanıklılık
 * 91 - 195: Konu Hakimiyeti, Zorlukları Aşma & Sabır
 * 196 - 256: 60 Günlük Deneme Sınavı Dönemi, Soğukkanlılık & Net Analizi
 * 257 - 270: Sınav Öncesi Zirve Güven, Sakinlik & Dinlenme
 */

export const MOTIVATION_QUOTES: readonly string[] = [
  // --- 1. DÖNEM: TEMEL KURMA, ALIŞKANLIK & DİSİPLİN (GÜN 1 - 90) ---
  "Disiplin, canın istemediğinde bile hedefine sadık kalmaktır. Bugün attığın ilk adım, yarınki büyük başarına temel olacak Yusuf.",
  "Büyük hedefler bir günde fethedilmez; her gün sabırla çözülen 20 soruyla inşa edilir.",
  "Yetenek sana kapıyı açar, ancak içeri girip orada kalmanı sağlayan tek şey disiplinli çalışmandır.",
  "Bugün masaya koyduğun her dakikalık odaklanma, sınav anındaki soğukkanlılığının teminatıdır.",
  "Zirveye tırmananlar dağa bakanlar değil, her gün bir adım daha yukarı adım atanlardır.",
  "Günün yorgunluğu geçicidir Yusuf; ancak kazandığın bilgi ve irade ömür boyu seninle kalır.",
  "Ertelemek gelecekteki huzurundan borç almaktır. Bugün görevini bitirdin, şimdi derin bir uykuyu hak ettin.",
  "Sadece sonuçlara değil, her gün sergilediğin emeğin asaletine odaklan. Başarı senin doğanda var.",
  "Zihnini bir bahçe gibi düşün; bugün çözdüğün her soru o bahçeye diktiğin değerli bir fidandır.",
  "Disiplinli bir gün, yastığa başını koyduğunda hissettiğin o derin iç huzurudur.",
  "En zor soru bile mantıklı parçalara bölündüğünde çözülür. Sabırlı zihin daima kazanır.",
  "Bugün öğrendiğin her yeni kural, LGS günü önüne çıkacak bir engeli önceden kaldırdı.",
  "Başarı büyük sıçramalarda değil, sessizce sürdürülen günlük tekrarlarda gizlidir Yusuf.",
  "Zorlandığın anlar pes etme vakti değil, beyninin kapasitesini genişlettiği anlardır.",
  "Bir maraton hızla değil, düzenli adımlarla kazanılır. Sen ritmini korumaya devam et.",
  "Yarın sabah daha güçlü uyanmak için bu gece zihnini dinlendir. Dinlenmek de disiplinin bir parçasıdır.",
  "Her gün çözülen 20 paragraf sorusu sadece Türkçeni değil, tüm derslerdeki anlama hızını artırır.",
  "Hayallerine giden yol, canın çalışmak istemediği günlerde gösterdiğin kararlılıktan geçer.",
  "Matematik sabır oyunudur Yusuf; pes etmeyen zihin her düğümü er ya da geç çözer.",
  "Yorulmak doğaldır, mola vermek haktır; ancak hedeften vazgeçmemek şampiyonların özelliğidir.",
  "Bugün gösterdiğin gayret yarınki Yusuf'a en güzel hediyendir. Kendinle gurur duy.",
  "Küçük günlük alışkanlıklar bir araya geldiğinde devasa bir başarı heykeli oluşturur.",
  "Zihninin gücünü hafife alma; düzenli çalıştıkça zor gelen soruların nasıl kolaylaştığını göreceksin.",
  "Başarı şans değil, planlı bir çalışmanın matematiksel sonucudur.",
  "Bugün bir sayfa daha fazla okudun, bir soru daha derin düşündün. İşte bu gerçek ilerlemedir.",
  "Uykunu ihmal etme Yusuf; beynin günün kazanımlarını uykuda kalıcı hafızaya kodlar.",
  "Disiplin, anlık istekleri gelecekteki büyük hedefler için feda edebilme olgunluğudur.",
  "Günün sonunda vicdanın rahatsa, en büyük zaferi kazanmışsın demektir.",
  "Kendine inanmak, çözemediğin sorunun üzerine cesaretle tekrar gitmektir.",
  "Her doğru cevap bir başarı, her yanlış cevap ise mükemmel bir öğrenme fırsatıdır.",
  "Yol uzun gibi görünse de bir günde sadece o günü yaşayabilirsin. Bugünü kazandın, tebrikler.",
  "Bugünkü 20 soruluk süre ölçümün, sınav günü zamana hükmetmenin provasıdır.",
  "Hata yapmaktan korkma; hata yapmayan sadece hiç denememiş olandır.",
  "Sabır, hedefe doğru ilerlerken zamanın sana çalışmasına izin vermektir.",
  "İçindeki potansiyel dışarıdaki tüm zorluklardan daha büyüktür Yusuf.",
  "Gereksiz telaşa yer yok; sakin, istikrarlı ve kararlı adımlar daima zafere ulaşır.",
  "Bugün bitirdiğin her ders, hedefin olan liseye açılan bir kapıdır.",
  "Disiplin bir kısıtlama değil, hayallerine ulaşmanı sağlayan en büyük özgürlüktür.",
  "Gözlerini hedeften ayırma, ancak adımlarını sadece bugüne odakla.",
  "Zorluklar seni yıldırmak için değil, ne kadar kararlı olduğunu sınamak için vardır.",
  "Bilgi çalıştıkça parıldayan bir kılıç gibidir. Sen onu her gün keskinleştiriyorsun.",
  "Bugün gösterdiğin özveri, LGS sonuç ekranında yüzündeki tebessüme dönüşecek.",
  "Sessiz sedasız çalışanlar, başarılarıyla en yüksek sesi çıkarırlar.",
  "Her gün düzenli uyumak, zihnine LGS için yapabileceğin en büyük yatırımdır.",
  "Bugünkü çalışman tamamdı; şimdi zihnini rahatlat ve yarın için enerji topla.",
  "Başarı başkalarıyla yarışmak değil, dünkü Yusuf'un bir adım önüne geçmektir.",
  "Azim, vazgeçmek için binlerce bahane varken devam etmek için tek bir neden bulmaktır.",
  "Her soru bir bilmecedir ve sen o bilmeceleri çözecek zekaya sahipsin.",
  "Karakter canın istemediği anlarda nasıl davrandığınla ölçülür; sen bugün disiplini seçtin.",
  "Yarınki başarıların tohumları bu geceki huzurlu uykunda yeşerecek.",
  "Odaklanma bir kastır Yusuf; her gün çalıştıkça daha da güçlenir.",
  "Hedefine olan inancın, karşılaştığın tüm yorgunluklardan daha üstündür.",
  "Kendine karşı dürüstçe gösterdiğin çaba asla karşılıksız kalmaz.",
  "Bugünün işini bitirdin. Şimdi zihnini kapat ve dinlenmenin keyfini çıkar.",
  "Bir soru bankasını bitiren şey sayfaları hızlı çevirmek değil, soruları derinlemesine anlamaktır.",
  "Gelecek, bugünden ona hazırlanan cesur zihinlere aittir.",
  "Hız acele etmek değildir Yusuf; hız, net düşünmenin doğal sonucudur.",
  "Bugünkü gayretin sessiz olabilir ama yarattığı etki geleceğinde çok büyük olacak.",
  "Zor konular seni korkutmasın; her karmaşık konu basit kuralların birleşimidir.",
  "Uykuna gösterdiğin özen, beynine gösterdiğin saygıdır.",
  "Planına sadık kaldığın her gün kendine olan saygın ve özgüvenin katlanarak artar.",
  "Yarını düşünerek kaygılanma; bugünün görevini yaptın ve görev tamamlandı.",
  "Şüphe zayıflatır, eylem güçlendirir. Sen eyleme geçtin ve bugün de kazandın.",
  "Zihnindeki tüm düşünceleri bir kenara bırak; şimdi uyku ve yenilenme saati.",
  "Her gün çözülen kaliteli sorular, zihnini bir satranç ustası kadar keskin yapar.",
  "LGS bir zeka testi değil, istikrarlı bir çalışma ve soğukkanlılık maratonudur.",
  "Bugün yaptığın tekrarlar, sınav anındaki reflekslerini inşa ediyor.",
  "Dinlenmek tembellik değil, verimliliğin vazgeçilmez bir şartıdır.",
  "Sabırla işlenen demir çeliğe dönüşür; sabırla çalışan öğrenci hedefine ulaşır.",
  "Bugünkü derslerin bitti, hedefine bir gün daha yaklaştın Yusuf.",
  "Kendini başkalarıyla değil, dünkü bilgin ve bugünkü kavrayışınla kıyasla.",
  "Zihnini boşalt, derin bir nefes al; bugün elinden gelenin en iyisini yaptın.",
  "Büyük hedefler korkak kalpleri ürkütür, cesur yüreklere ise kanat takar.",
  "Çözemediğin soru sana en çok şey öğreten sorudur; onu yarın kolayca fethedeceksin.",
  "İstikrar, vasatlığı dehaya dönüştüren en güçlü güçtür.",
  "Gecenin sessizliği yarının umut dolu aydınlığına gebedir. Huzurla uyu.",
  "Bugün gösterdiğin sabır, yarın sınav kağıdında netlere dönüşecek.",
  "Hedefin netse, yolundaki engebeler sadece adımlarını sağlamlaştırır.",
  "Her gün bir tuğla koydun; LGS 2027 kalesi hızla yükseliyor Yusuf.",
  "Zorluklar karşısında gülümseyebilen bir iradeyi hiçbir sınav durduramaz.",
  "Kendine inan; çünkü sen inandığında başaramayacağın hiçbir şey yoktur.",
  "Bugünkü 20 soruluk blok, zihinsel dayanıklılığını bir kademe daha yukarı taşıdı.",
  "Geceye huzurla veda et, yarın yeni bilgiler öğrenmenin heyecanıyla doğacak.",
  "Zaman en adil kaynaktır; onu nasıl kullandığın senin kim olduğunu belirler.",
  "Bugün zamanını geleceğin için kullandın. Tebrikler Yusuf.",
  "Kendini dinlendir; en keskin balta bile düzenli olarak dinlendirilmeli ve bilenmelidir.",
  "Her gün biraz daha güçleniyorsun; bunu belki hemen hissetmezsin ama sınavda göreceksin.",
  "İrade kas gibidir; bugün de o kası hakkıyla çalıştırdın.",
  "Yıldızlar karanlık olmadan parlamaz; zorluklar olmadan başarı taçlanmaz.",
  "Bugün 1. dönemin temel taşlarını sağlam koydun. Yarın yeni bir gün!",

  // --- 2. DÖNEM: KONU PEKİŞTİRME, DERİNLEŞME & SABIR (GÜN 91 - 195) ---
  "Konular derinleştiğinde heyecanlan; çünkü tam da bu noktada fark yaratmaya başlıyorsun Yusuf.",
  "Bir soruyu anlamak, yüz soru ezberlemekten çok daha değerlidir.",
  "Zorluk seviyesi arttıkça senin problem çözme gücün de aynı oranda artıyor.",
  "Yanlışlar havuzuna eklediğin her soru, LGS'de cepte sayılacak garanti bir net adayıdır.",
  "Odaklanmış bir saat, dağınık bir tam günden çok daha verimlidir.",
  "Sınırlarını zorlamaktan çekinme; büyüme sadece konfor alanının bittiği yerde başlar.",
  "Sabır, meyvesi tatlı olan en köklü ağaçtır. Sen o ağacı her gün suluyorsun.",
  "Matematikte yeni nesil sorular bir hikayedir; sen o hikayenin kahramanısın Yusuf.",
  "Bugün pes etmeyen tarafın kazandı; yarın da aynı kararlılıkla devam edeceksin.",
  "Bir konuyu tam kavramak zaman alır; acele etme, sindirerek öğren.",
  "Kendine güven; çünkü bu masada harcadığın saatlerin şahidi sensin.",
  "Bugün çözdüğün zor sorular yarın senin en kolay rutinine dönüşecek.",
  "Akşam dinlenmesi bir ödül değil, yarının yüksek performansının zorunlu yakıtıdır.",
  "Her hata, doğru cevaba giden yolda aydınlatıcı birer deniz feneridir.",
  "Fen Bilimleri mantıktır, Türkçe kavrayıştır, Matematik stratejidir. Sen üçünde de ustalaşıyorsun.",
  "Zihnini olumsuz seslere kapat; sadece bugünkü hedefine ve gelişimine kulak ver.",
  "Bugün attığın düğümler yarınki başarı dokusunu oluşturacak.",
  "Yusuf, disiplinli bir öğrencinin önünde durabilecek hiçbir sınav yoktur.",
  "Günün tüm görevleri tamamlandıysa, geceye zaferle gülümsenebilir.",
  "Pes etmeyi düşündüğün an, hedefine en çok yaklaştığın andır.",
  "Derin bir uyku zihnini tazeler, yeni bağlantılar kurmanı kolaylaştırır.",
  "Bugün öğrendiğin formül sadece bir bilgi değil, gelecekteki kapıların anahtarıdır.",
  "Kararlılık, engelleri basamağa dönüştürme sanatıdır.",
  "Yaptığın her soru analizi, LGS'deki olası tuzakları önceden keşfetmektir.",
  "Kendine şefkat göster; mükemmel olmak zorunda değilsin, istikrarlı olman yeterlidir.",
  "Zirvedeki rüzgar sert eser ama manzarası her zahmete değerdir.",
  "Bugün kendine bir kez daha kanıtladın: Sen başladığın işi bitirenlerdensin.",
  "Soru çözerken gösterdiğin dikkat, zihninin en değerli hazinesidir.",
  "Dinlenmek, yayını gerip yarınki oku daha uzağa fırlatmak gibidir.",
  "Her günkü 20 soru, zihnini bir keskin nişancı titizliğine ulaştırıyor.",
  "Zor sorular zayıf iradeleri eler, güçlü iradeleri ise parlatır Yusuf.",
  "Bugün döktüğün her damla zihinsel çaba, geleceğine yazdığın bir mektuptur.",
  "Sessizce çalış, disiplinini bozma; başarı seni herkesin önünde alkışlatacaktır.",
  "Uykuna saygı duy; çünkü rüyalarındaki başarı ancak dinlenmiş bir zihinle gerçeğe dönüşür.",
  "Konuların birbiriyle nasıl bağlandığını fark ettiğin an, öğrenmenin zevkine varacaksın.",
  "Her gün küçük bir zaferdir; bugünkü zaferini kutla ve dinlenmeye çekil.",
  "Kendini dünle kıyasla; ne kadar çok şey öğrendiğini göreceksin.",
  "Zihninde şüpheye yer açma; planın sağlam, hedefin belli ve adımların güçlü.",
  "Bir problemi çözemediğinde nefes al, bakış açını değiştir ve tekrar dene.",
  "İstikrar, imkansız gibi görünen dağları kum tanesine çevirir.",
  "Bugün çalıştığın her konu başlığı, LGS karnende bir gurur madalyası olacak.",
  "Dinlenmiş bir beyin, yorgun bir beyinden on kat daha hızlı öğrenir.",
  "Kendini motive etmek için dışarıya bakma; hedefin senin kendi içinde parlıyor.",
  "Zorluk seviyesi yüksek sorular, LGS şampiyonlarının antrenman sahasıdır.",
  "Bugün gösterdiğin azim, karakterinin ne kadar sağlam olduğunun kanıtıdır Yusuf.",
  "Yarın yeni bir sayfa açılacak; bugün görevini tamamlamış olmanın huzuruyla uyu.",
  "Hız acelecilik değildir; hız, konuyu çok iyi anlamanın doğal meyvesidir.",
  "Sakin ol; panik hata yaptırır, soğukkanlılık doğru cevabı buldurur.",
  "Bugün çözdüğün her paragraf, okuma ve analiz hızını bir basamak daha yukarı çıkardı.",
  "Zaman senin dostundur; ona saygı duydukça o da senin lehine çalışır.",
  "Geceleyin dinlenmeyen zihin, gündüz berrak düşünemez. Güzelce uyu.",
  "Kendi hızında ilerle; başkalarının temposu seni ilgilendirmez, senin planın sana özeldir.",
  "Başarıya giden yolda kestirme yoktur; en güvenli yol adım adım ilerlenen yoldur.",
  "Bugün yaptığın çalışma yarınki özgüveninin teminatıdır.",
  "Kendine inan Yusuf; bugüne kadar ne kadar çok şey başardığını hatırla.",
  "Bir yanlışı tespit etmek, bir doğruyu öğrenmenin yarısıdır.",
  "Zihnini sakinleştir; bugün elinden gelenin en iyisini yaptın ve bu fazlasıyla yeterli.",
  "LGS 2027 hedefine adım adım yaklaşıyorsun; her geçen gün daha hazırsın.",
  "Disiplinli çalışmanın verdiği iç huzuru hiçbir eğlence veremez.",
  "Zihnini dinlendir ki yarın yeni bilgiler için tertemiz bir alan açılsın.",
  "Çözemediğin soruya teşekkür et; sana bilmediğin bir detayı öğretti.",
  "Azimle yürüyen bir yolcunun önünde hiçbir dağ duramaz.",
  "Bugün döktüğün her damla alın teri yarın gurur gözyaşlarına dönüşecek.",
  "Kendinle barışık ol; her gün en iyi günün olmak zorunda değil, ama her gün devam etmek zorundasın.",
  "Sessizce ve istikrarla çalışmaya devam et; zirve seni bekliyor Yusuf.",
  "Uykuna çekilmeden önce bugün öğrendiğin üç güzel şeyi hatırla ve huzurla gözlerini kapat.",
  "Zor sorular zihnin ağırlık antrenmanıdır; bugün kaslarını bir kez daha güçlendirdin.",
  "Her gün atılan küçük adımlar, devasa mesafeleri kat etmenin tek yoludur.",
  "Sabır en büyük erdemdir; sonucu beklemeden önce sürece güven.",
  "Bugün de planına sadık kaldın. İşte gerçek irade budur!",
  "Yarın güneş senin için doğacak; dinlenmiş ve tazelenmiş olarak güne başlayacaksın.",
  "LGS'de karşına çıkacak sorular bu masada çözdüğün sorulardan farklı olmayacak.",
  "İçindeki başarma arzusu karşılaştığın tüm engellerden daha güçlüdür.",
  "Kendine güven Yusuf; bu yolculukta gösterdiğin cesaret takdire şayan.",
  "Bugün bir konunun daha üstünü çizdin; LGS müfredatı önünde hızla eriyor.",
  "Zihnini dinlendir, bedenini gevşet; yarınki başarılar bu geceki uykuda mayalanır.",
  "Disiplin seni sadece LGS'de değil, tüm hayatında lider yapacak bir güçtür.",
  "Doğru yoldasın, doğru hızdasın ve doğru adımları atıyorsun. Asla şüphe etme.",
  "Bugün öğrendiğin her püf noktası sınavda sana dakikalar kazandıracak.",
  "Sakin ol, derin nefes al; başarı sakin ve odaklanmış zihinleri sever.",
  "Günün bitti, sorumluluğunu yerine getirdin. Şimdi deliksiz bir uyku vakti.",
  "Her gün çözülen sorular zihninde silinmez izler bırakır; emeklerin asla kaybolmaz.",
  "Kendi potansiyeline saygı duy; yapabileceklerinin henüz yarısını bile görmedin.",
  "Bugün gösterdiğin sabır yarınki netlerine yansıyacak.",
  "Zorluklar iradeni biler; sen her geçen gün daha keskin bir zihne kavuşuyorsun Yusuf.",
  "İnanmak başarmanın yarısıdır; kalan yarısı ise bugün sergilediğin disiplindir.",
  "Yarın yeni bir gün ve yeni fırsatlar var. Bugünlük görevin bitti, huzurla uyu.",
  "Sınav anında hatırlayacağın şey bu geceki huzurlu uykun ve çalışmaların olacak.",
  "Her adım seni hedefine bir adım daha yaklaştırıyor. Vazgeçmek senin kitabında yok.",
  "Konuları bitirdikçe içindeki özgüvenin nasıl yükseldiğini hisset. Harikasın!",
  "Bugünkü gayretin için teşekkürler Yusuf. Şimdi zihnini dinlendirme saati.",
  "Zorluklar karşısında gösterdiğin dik duruş, yarınki şampiyonluğunun ayak sesleridir.",
  "Sakin, istikrarlı ve emin adımlarla zirveye doğru yürüyorsun.",
  "Bugün 13 Nisan konu bitirme hedefine bir adım daha yaklaştın. Tebrikler!",
  "Tüm konular bittiğinde arkana bakıp gurur duyacaksın; şimdi o gurura doğru uyu.",

  // --- 3. DÖNEM: 60 GÜN DENEME SINAVI DÖNEMİ, SOĞUKKANLILIK & NET ANALİZİ (GÜN 196 - 256) ---
  "Deneme sınavları seni ölçmek için değil, hatalarını erkenden yakalayıp düzeltmen için birer hediyedir.",
  "Bugünkü deneme sonucun ne olursa olsun, yarınki LGS için en değerli tecrübedir Yusuf.",
  "Sınav anında sadece sorularla değil, heyecanınla da dans etmeyi öğreniyorsun.",
  "Her deneme gerçek LGS'nin provasıdır; sen provada ustalaşan bir başrol oyuncususun.",
  "Netlerin dalgalanması doğaldır; önemli olan her denemeden sonra yaptığın derin yanlış analizidir.",
  "Süre yönetimi denemelerle oturur; sakin ol, turlama taktiğini uygula ve kendine güven.",
  "Bugün yaptığın her yanlış, LGS günü yapmayacağın bir hatadır. Yanlışlarına teşekkür et.",
  "Zirve artık ufukta göründü Yusuf; şimdi soğukkanlılığını koruma ve odaklanma vakti.",
  "Denemede zor bir soruyla karşılaştığında gülümse; 'seni sonraya bırakıyorum' de ve devam et.",
  "LGS bilgiyi değil, baskı altında sakin kalabilme sanatını ölçer. Sen bu sanatta ustalaşıyorsun.",
  "Bugün tam 90 soruluk gerçek bir deneme çözdün; zihinsel kondisyonun zirveye ulaştı.",
  "Netler sayılardan ibarettir; senin gerçek gücün ise asla pes etmeyen iradendir.",
  "Sınav provası tamamlandı; şimdi zihnini gevşet ve yarınki yeni denemeye hazırlan.",
  "Hatalarını analiz ettikçe sınav kağıdındaki olası tuzakları birer birer temizliyorsun.",
  "Bugünkü deneme sana hangi konuya biraz daha bakman gerektiğini fısıldadı; bu bir eksik değil fırsattır.",
  "Sakin kalabilen öğrenci, en zor sorularda bile gizli ipuçlarını rahatça görür.",
  "Kendine güven Yusuf; 60 gün boyunca her gün deneme çözmek muazzam bir cesaret ve disiplindir.",
  "LGS günü salona girdiğinde yabancılık hissetmeyeceksin; çünkü bunu 60 kez yapmış olacaksın.",
  "Her deneme zihnindeki hız ve doğruluk dengesini milimetrik olarak ayarlıyor.",
  "Bugünkü sınav bitti, analizi yapıldı. Artık zihnini tamamen serbest bırakma vakti.",
  "Zamana karşı yarışma, zamanla birlikte hareket et. Kronometre senin düşmanın değil yol arkadaşındır.",
  "Netlerin yükselirken alçakgönüllü ol, düştüğünde ise inancını asla yitirme.",
  "Bugün çözdüğün deneme, gerçek sınavdaki soğukkanlılığının teminatıdır.",
  "Soruyla inatlaşma; gerektiğinde geçmeyi bilmek en büyük sınav stratejisidir Yusuf.",
  "Uykuna her zamankinden çok özen göster; deneme yorgunluğu sadece derin bir uykuyla atılır.",
  "LGS'de sürpriz yoktur; bu masada gördüğün tüm varyasyonlar sınavda karşına çıkacak.",
  "Sen aylardır emek verdin; bu emekler sınav anında senin en büyük koruyucu kalkanın olacak.",
  "Bugünkü denemede dikkat ettiğin o küçük ayrıntı, sınavda seni binlerce kişinin önüne geçirecek.",
  "Kendini deneme puanıyla tanımlama; sen azmin, disiplinin ve öğrenme tutkunun toplamısın.",
  "Her gün bir tam deneme çözmek bir şampiyonluk antrenmanıdır. Sen o şampiyonsun Yusuf.",
  "Bugün de masadan başın dik kalktın. Şimdi derin ve huzurlu bir uyku vakti.",
  "Sınav salonunda yapacağın tek şey, bu odada her gün yaptığın şeyi bir kez daha tekrarlamak.",
  "Heyecan doğaldır ve gereklidir; o heyecanı pozitif bir odaklanma enerjisine dönüştür.",
  "Yanlış analizini tamamladın, eksiklerini gördün. İşte zafere giden yol tam olarak budur.",
  "Zihnini boşalt; bugünün tüm soruları bitti. Yarın yepyeni bir enerjiyle başlayacaksın.",
  "Sabırla ördüğün bu ağ, sınav günü en güzel başarıyı yakalayacak.",
  "Bugünkü netlerin senin potansiyelinin sadece bir kısmı; LGS'de zirveyi göreceksin.",
  "Korkacak hiçbir şey yok; çünkü sen hazırlıksız değilsin, sen aylarını bu hedefe adadın.",
  "Deneme bittiğinde hissettiğin o tatlı yorgunluk, emeğin en asil kanıtıdır.",
  "Yusuf, kendine olan inancın en zor denemeden bile daha güçlü olsun.",
  "Zihnini sakinleştir; sınavlar geçer, bilgiler kalır, kazandığın disiplin ise ömür boyu sürer.",
  "Bugünkü denemede süreyi harika yönettin. Bu alışkanlık sınavda en büyük avantajın olacak.",
  "Hatalardan korkmayan bir zihin durdurulamaz bir güçtür.",
  "Her deneme bir basamak; sen 60 basamaklı bu merdivenin zirvesine emin adımlarla çıkıyorsun.",
  "Bugün yaptığın hatalar sana yarınki LGS tam puanını hediye edecek.",
  "Kendinle gurur duy; bu yoğun tempoda her gün aynı ciddiyetle masaya oturmak büyük bir başarıdır.",
  "Geceye huzurla bırak kendini; beynin bugün çözdüğü tüm stratejileri yerine oturtsun.",
  "LGS bir maratonun son 100 metresi gibidir; şimdi tempoyu koruma ve dik durma vakti.",
  "Sakin nefes al; sınav kağıdı sadece bir kağıttır, senin zekan ise sınırsız bir potansiyeldir.",
  "Bugünkü denemenin tüm analizleri tamamlandı. Görev bitti, şimdi şarj olma zamanı.",
  "Zor bir denemeyle karşılaştığında sevin; çünkü gerçek LGS bundan daha zor olmayacak.",
  "Sen bu sürecin her anında emek verdin, ter döktün. Karşılığını mutlaka alacaksın.",
  "Bugün gösterdiğin soğukkanlılık yarın sınav anında otomatik olarak devreye girecek.",
  "Zihnini dinlendir Yusuf; yarınki deneme senin yeni bir rekor kırma sahandır.",
  "Emek asla kaybolmaz; doğanın kanunu budur. Sen ektin, günü geldiğinde biçeceksin.",
  "Her deneme sana sınav salonunun havasını solutuyor; artık hiçbir şey seni şaşırtamaz.",
  "Bugün de görevin başındaydın ve harika bir iş çıkardın. Huzurla uyu.",
  "Kendine inan; çünkü ailen, öğretmenlerin ve en önemlisi kendi vicdanın seninle gurur duyuyor.",
  "Son 60 günün her birinde kendini aştın. Zirveye çok az kaldı Yusuf!",
  "Dinlenmiş bir zihin, en karmaşık LGS sayısal sorusunu bile berrakça çözer.",
  "Bugünkü deneme geride kaldı; yarın yepyeni bir gün ve yepyeni bir fırsat seni bekliyor.",

  // --- 4. DÖNEM: SINAV ÖNCESİ SAKİNLİK, İNANÇ & ZİRVE GÜVEN (GÜN 257 - 270) ---
  "Aylardır verdiğin emeğin karşılığını alma vakti yaklaşıyor; için rahat, zihnin sakin olsun Yusuf.",
  "Sen elinden gelenin en iyisini yaptın. Şimdi sürecin meyvelerini toplama zamanı.",
  "LGS senin değerini belirlemez; sadece aylardır sergilediğin muhteşem disiplini tesciller.",
  "Sakin ol; bildiğin sorularla karşılaşacaksın. Yaptığın binlerce sorunun aynısı orada olacak.",
  "Zihnini gereksiz düşüncelerden arındır; sen bir şampiyon gibi çalıştın, bir şampiyon gibi tamamlayacaksın.",
  "Bugün kendine teşekkür et; bu zorlu maratonda gösterdiğin sabır ve azim için kendinle gurur duy.",
  "Artık yeni bir şey öğrenme telaşı yok; sadece bildiklerine güvenme ve sakin kalma vakti.",
  "Derin bir nefes al; nefesini verirken tüm kaygılarını dışarı bırak. Sen hazırsın Yusuf.",
  "Bu gece uykuna her zamankinden daha çok sarıl; dinlenmiş bir beden ve berrak bir zihin en büyük gücündür.",
  "Sınav salonunda yapacağın tek şey, aylardır bu masada yaptığın sakin soru çözümlerini tekrarlamak.",
  "Yarınlar emek verenleri daima ödüllendirir. Senin emeğin ise göz kamaştırıcı.",
  "Kendine güven; girdiğin salondan başın dik ve yüzün gülerek çıkacaksın.",
  "Bu yolculukta kazandığın irade ve disiplin, LGS'den alacağın puandan çok daha değerlidir.",
  "Son günlerde zihnini huzurla doldur. Başarı sakinliği sever Yusuf.",
  "Kendini hazır hisset; arkanda 256 günlük sağlam bir çalışma kalesi var.",
  "Gözlerini kapat ve hedefine ulaştığın anın mutluluğunu hayal et; o an çok yakın.",
  "Sınav sadece bir basamak, sen ise zirveye yürüyen kararlı bir gençsin.",
  "Zihnindeki tüm bilgiler yerli yerinde; yarın ihtiyacın olduğunda hepsi berrakça açığa çıkacak.",
  "Heyecanını kucakla; o heyecan senin başarma tutkundan besleniyor.",
  "Bu gece uykunun huzurlu kollarında dinlen; şampiyonlar son hazırlığı derin uykuda yapar.",
  "Attığın her adımla gurur duyuyoruz Yusuf; sen harika bir çalışma dönemi geçirdin.",
  "Sınav anında derin bir nefes al ve gülümse; çünkü sen bu başarıyı sonuna kadar hak ettin.",
  "Yarın senin günün; tüm emeklerin meyvesini toplayacaksın. Kendine güven!",
  "Ve unutma Yusuf: En büyük zafer, pes etmeden son güne kadar savaşmış olmaktır. Tebrikler şampiyon!",
] as const;

/**
 * Returns a unique daily motivation quote tailored for Yusuf based on the study plan day or date.
 * Exactly 270 unique quotes ensuring zero repetitions across the 256 study days + buffer days.
 */
export function getDailyMotivationQuote(options?: {
  dateStr?: string;
  dayNumber?: number;
}): string {
  // 1. If explicit dayNumber is provided (1-based index)
  if (options?.dayNumber && options.dayNumber > 0) {
    const idx = (options.dayNumber - 1) % MOTIVATION_QUOTES.length;
    return MOTIVATION_QUOTES[idx];
  }

  // 2. If date string is provided (YYYY-MM-DD)
  if (options?.dateStr) {
    const planStart = new Date("2026-10-01T00:00:00Z").getTime();
    const target = new Date(`${options.dateStr}T00:00:00Z`).getTime();
    const diffDays = Math.floor((target - planStart) / (1000 * 60 * 60 * 24));

    if (diffDays >= 0) {
      const idx = diffDays % MOTIVATION_QUOTES.length;
      return MOTIVATION_QUOTES[idx];
    } else {
      // Pre-plan days: map deterministically based on date digits
      const prePlanHash = Math.abs(diffDays) % 15;
      return MOTIVATION_QUOTES[prePlanHash];
    }
  }

  // 3. Default fallback: Day 1 quote
  return MOTIVATION_QUOTES[0];
}
